# Library Initialization

In [83]:
import pandas as pd
df = pd.read_csv("data/electronics_store.csv")

# Dataset Exploration

In [84]:
df.head()

  TransactionID Product     Category  Quantity  UnitPrice  CustomerID Country   OrderDate
0            T1   Phone       Mobile         3      500.0       119.0      UK  2025-02-14
1            T2   Mouse  Accessories         4       15.0       136.0   Italy  2025-01-04
2            T3  Laptop    Computers         1      900.0       147.0   Italy  2025-03-10
3            T4  Tablet       Mobile         3      300.0       145.0  France  2025-01-12
4            T5  Laptop    Computers         3      900.0       136.0  France  2025-01-01

In [85]:
df.tail()

    TransactionID  Product     Category  Quantity  UnitPrice  CustomerID  Country   OrderDate
315           T71   Laptop    Computers         2      900.0         NaN       UK  2025-03-04
316           T44   Laptop    Computers         4      900.0       124.0       UK  2025-04-22
317            T3   Laptop    Computers         1      900.0       147.0    Italy  2025-03-10
318          T237  Monitor      Display         2      200.0       107.0  Germany  2025-01-01
319          T134    Mouse  Accessories         1       15.0       124.0    Italy  2025-01-06

In [86]:
df.shape

(320, 8)

In [87]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionID  320 non-null    str
 1   Product        320 non-null    str
 2   Category       320 non-null    str
 3   Quantity       320 non-null    int64
 4   UnitPrice      320 non-null    float64
 5   CustomerID     301 non-null    float64
 6   Country        320 non-null    str
 7   OrderDate      320 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 20.1 KB

# Understanding Dataset Structure

In [88]:
df.columns

Index(['TransactionID', 'Product', 'Category', 'Quantity', 'UnitPrice',
       'CustomerID', 'Country', 'OrderDate'],
      dtype='str')

In [89]:
df.dtypes

TransactionID        str
Product              str
Category             str
Quantity           int64
UnitPrice        float64
CustomerID       float64
Country              str
OrderDate            str
dtype: object

- categorical: "TransactionID", "Product", "Category", "Country", and "OrderDate"
- numerical: "Quantity", "UnitPrice", and "CustomerID"

# Data Quality Check

In [90]:
df.duplicated().sum()

np.int64(20)

In [91]:
df[df["UnitPrice"] <= 0]

Empty DataFrame
Columns: [TransactionID, Product, Category, Quantity, UnitPrice, CustomerID, Country, OrderDate]
Index: []

In [92]:
df[df["Quantity"] < 0]

    TransactionID     Product     Category  Quantity  UnitPrice  CustomerID  Country   OrderDate
10            T11      Laptop    Computers        -1      900.0       121.0    Spain  2025-01-27
20            T21      Tablet       Mobile        -1      300.0       102.0  Germany  2025-04-16
41            T42  Headphones        Audio        -1       60.0       143.0  Germany  2025-04-26
82            T83      Tablet       Mobile        -1      300.0       113.0   France  2025-01-12
90            T91  Headphones        Audio        -1       60.0       122.0    Spain  2025-04-27
106          T107       Phone       Mobile        -1      500.0       101.0       UK  2025-03-22
111          T112      Laptop    Computers        -1      900.0       122.0   France  2025-03-03
188          T189    Keyboard  Accessories        -1       25.0       144.0    Italy  2025-02-16
245          T246  Headphones        Audio        -1       60.0       117.0  Germany  2025-04-16
312           T11      Laptop    Computers        -1      900.0       121.0    Spain  2025-01-27

In [93]:
df.dtypes

TransactionID        str
Product              str
Category             str
Quantity           int64
UnitPrice        float64
CustomerID       float64
Country              str
OrderDate            str
dtype: object

# Duplicate Handling

In [94]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

# Invalid Data Handling

In [95]:
df["Quantity"] = df["Quantity"].apply(lambda x: x if x >= 0 else df['Quantity'].median())
df[df["Quantity"] < 0]

Empty DataFrame
Columns: [TransactionID, Product, Category, Quantity, UnitPrice, CustomerID, Country, OrderDate]
Index: []

# Data Type Fixing

In [96]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])
df.dtypes

TransactionID               str
Product                     str
Category                    str
Quantity                float64
UnitPrice               float64
CustomerID              float64
Country                     str
OrderDate        datetime64[us]
dtype: object

# Feature Creation

In [97]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]
df.sample()

    TransactionID  Product Category  Quantity  UnitPrice  CustomerID Country  OrderDate  Revenue
131          T132  Monitor  Display       1.0      200.0       114.0   Spain 2025-03-28    200.0

# Outlier Detection

In [110]:
for col in ["Quantity", "UnitPrice"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q1 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col]
    
    print(f"{col} Outliers: {outliers.to_list()}, Total: {outliers.count()}")

Quantity Outliers: [], Total: 0
UnitPrice Outliers: [900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0], Total: 55

# Cleaning Verification

In [112]:
df.duplicated().sum()

np.int64(0)

In [114]:
df.isnull().sum()

TransactionID     0
Product           0
Category          0
Quantity          0
UnitPrice         0
CustomerID       18
Country           0
OrderDate         0
Revenue           0
dtype: int64

In [119]:
df["Product"].unique()

<StringArray>
['Phone', 'Mouse', 'Laptop', 'Tablet', 'Monitor', 'Headphones', 'Keyboard']
Length: 7, dtype: str

In [120]:
df["Category"].unique()

<StringArray>
['Mobile', 'Accessories', 'Computers', 'Display', 'Audio']
Length: 5, dtype: str

In [121]:
df["Country"].unique()

<StringArray>
['UK', 'Italy', 'France', 'Spain', 'Germany']
Length: 5, dtype: str

# Insight Preparation

The cleaned data can be used to identify objectives (top products, revenue, customer behavior, etc.)